1단계 학습 테스트 실습 추가
Jeongmin94/java-racingcar pull request #1
Opened 2022-09-03 03:02 UTC by Jeongmin94

- String 클래스에 대한 테스트 코드 추가
- Set 클래스에 대한 테스트 코드 추가

2022-09-03 07:30 UTC, Wu22e requested changes
화이팅임다 ~ 리뷰 확인하고 다시올려주시면 감사하겟슴다

2022-09-03 07:30 UTC, Wu22e commented on src/test/java/SetTest.java
> +        assertThat(numbers.contains(value)).isEqualTo(true);
`.isTrue()` 를 사용 하는 것도 좋아요

2022-09-03 07:30 UTC, Wu22e commented on src/test/java/SetTest.java
> +    @DisplayName("contains 메서드 사용해서 set의 데이터 확인")
DisplayName이 해당 메서드의 테스트를 명확히 드러낼 수 있으면 좋을 것 같아요.
지금은 위의 containsTest 메서드와 네이밍이 같은데, 어떤 테스트를 위한 건지 해당 메서드의 명확한 의미를 지어주면 좋을 것같네요

2022-09-03 07:30 UTC, Wu22e commented on src/test/java/StringTest.java
> +        assertThat(oneTwoArr).hasSize(2);
`.hasSize()` 사용 좋군요~ 👍

2022-09-03 07:30 UTC, Wu22e commented on src/test/java/StringTest.java
> +    @DisplayName("charAt 메서드 사용했을 때 예외 처리")
어떤 예외 처리인지 조금 더 구체적이면 좋을 것 같아요

2022-09-03 07:30 UTC, Wu22e commented on src/test/java/StringTest.java
> +}
assertThatExceptionOfType 메서드 테스트도 추가해보는게 어떨까요?

2022-09-04 14:50 UTC, Jeongmin94 commented on src/test/java/StringTest.java
> +}
`assertThatThrownBy`, `assertThatExceptionOfType` 두 가지 모두 거의 동일한 역할과 기능을 가지고 있는데, 경우에 따라 사용하는 메서드가 달라지나요?

2022-09-05 07:44 UTC, Wu22e requested changes

2022-09-05 14:25 UTC, Jeongmin94 commented on src/test/java/StringTest.java
> +    void charAtWithStringIndexOutOfBoundsExceptionAndAssertThatExceptionOfTypeTest() {
👍 👍 👍

2022-09-05 14:26 UTC, merged